INSERT INTO users(name,username,email,password,country,style) VALUES('Aarav Mehta','aarav_mehta','demo@globetrotter.com','$2y$10$7Gx9Kf3M0K4Gqf3Zb1w5E.0mGf7QhZ7Y3oQv7hH5s7m6YvJfQe4q','India','Balanced');
INSERT INTO trips(user_id,name,start_date,end_date,description,budget,cover,style,is_public,share_token) VALUES(1,'Japan in Spring','2026-04-05','2026-04-15','Cherry blossoms, quiet streets and unforgettable food.',120000,'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1000&q=80','Balanced',1,'jp-spring-26');
INSERT INTO stops(trip_id,city,start_date,end_date) VALUES(1,'Tokyo','2026-04-05','2026-04-09'),(1,'Kyoto','2026-04-09','2026-04-13'),(1,'Osaka','2026-04-13','2026-04-15');
INSERT INTO activities(stop_id,name,time,cost,type,description) VALUES(1,'Shibuya & Harajuku walk','10:00 AM',1200,'Sightseeing','Explore the energetic heart of Tokyo.'),(1,'Sushi omakase dinner','07:30 PM',6500,'Food','A special tasting-menu evening.'),(2,'Fushimi Inari Shrine','08:00 AM',0,'Culture','Walk through the iconic torii gates.'),(2,'Gion evening stroll','06:00 PM',900,'Sightseeing','Traditional streets and tea houses.'),(3,'Dotonbori food trail','06:30 PM',2200,'Food','Try Osaka classics along the canal.');
INSERT INTO discover(name,country,description,image,cost_index,type,default_cost,popular) VALUES
('Tokyo','Japan','Neon nights, timeless temples and endless food discoveries.','https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=80','$$$','City',18000,10),
('Kyoto','Japan','Lantern-lit lanes, shrines, gardens and slow mornings.','https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80','$$','Culture',12000,9),
('Bali','Indonesia','Warm beaches, rice terraces and restorative escapes.','https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80','$$','Relaxation',9000,8),
('Paris','France','Art, cafés, architecture and unforgettable city walks.','https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=80','$$$','City',22000,9),
('Swiss Alps','Switzerland','Mountain views, scenic trains and crisp alpine air.','https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=900&q=80','$$$$','Adventure',30000,7),
('Istanbul','Türkiye','A vivid mix of bazaars, mosques and Bosphorus sunsets.','https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=900&q=80','$$','Culture',11000,8);

INSERT INTO community_posts(user_id,title,content,destination,category,style,likes,comments,created_at) SELECT 1,'A calm weekend in Kyoto','If you want a slower Japan experience, stay near Higashiyama and start sightseeing before 8 AM. The quiet streets are worth the early wake-up.','Kyoto','tip','Relaxed',28,6,'2026-08-20 09:15:00' WHERE NOT EXISTS (SELECT 1 FROM community_posts);
INSERT INTO community_posts(user_id,title,content,destination,category,style,likes,comments,created_at) SELECT 1,'Best street food finds','I kept the food budget low by exploring local markets and small neighbourhood stalls instead of tourist-heavy restaurants.','Osaka','food','Budget',42,11 WHERE (SELECT COUNT(*) FROM community_posts)=1;
INSERT INTO community_posts(user_id,title,content,destination,category,style,likes,comments,created_at) SELECT 1,'What I learned from my first solo trip','Leave some space in the itinerary. My favourite moments came from unplanned walks, local conversations and changing plans when the weather shifted.','Tokyo','experience','Adventure',35,8 WHERE (SELECT COUNT(*) FROM community_posts)=2;
INSERT INTO community_posts(user_id,title,content,destination,category,style,likes,comments,created_at) SELECT 1,'A simple way to save on transport','Compare day passes with individual fares before buying. For multi-city trips, check regional passes only after mapping your actual travel days.','Japan','budget','Balanced',51,14 WHERE (SELECT COUNT(*) FROM community_posts)=3;
INSERT INTO community_posts(user_id,title,content,destination,category,style,likes,comments,created_at) SELECT 1,'Small safety habit that helped me','Save your hotel address offline, keep a backup payment method separate, and share your daily plan with someone you trust.','Kyoto','safety','Balanced',24,5 WHERE (SELECT COUNT(*) FROM community_posts)=4;

INSERT INTO admin_users(username,email,password,name) VALUES('admin','admin@globetrotter.com','$2y$12$ibEmQcGebWOTYqnU9vCmTuyVhO1IWag9eFOtsFNf9SqhKEgIkLplm','GlobeTrotter Admin');
