const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function adminApi(action,options={}){const r=await fetch('../backend/admin_api.php?action='+action,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
let adminState={admin:null,data:null,section:'overview'};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}
async function initLogin(){try{const d=await adminApi('me');if(d.admin)location.href='admin.html'}catch(e){}$('#adminLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();$('#adminError').textContent='';try{await adminApi('login',{method:'POST',body:JSON.stringify({login:$('#adminLogin').value,password:$('#adminPassword').value})});location.href='admin.html'}catch(err){$('#adminError').textContent=err.message}})}
async function initPanel(){try{const me=await adminApi('me');if(!me.admin){location.href='admin-login.html';return}adminState.admin=me.admin;$('#adminName').textContent=me.admin.name;adminState.data=(await adminApi('analytics'));renderAdmin();}catch(e){location.href='admin-login.html';return}$$('.admin-nav,.admin-tab').forEach(b=>b.onclick=()=>{adminState.section=b.dataset.section;$$('.admin-nav,.admin-tab').forEach(x=>x.classList.toggle('active',x.dataset.section===adminState.section));renderAdmin()});$('#adminLogout').onclick=async()=>{await adminApi('logout',{method:'POST'});location.href='admin-login.html'};['adminSearch','adminGroup','adminFilter','adminSort'].forEach(id=>$('#'+id)?.addEventListener('input',renderAdmin));['adminGroup','adminFilter','adminSort'].forEach(id=>$('#'+id)?.addEventListener('change',renderAdmin))}
function renderAdmin(){const d=adminState.data;if(!d)return;const c=$('#adminContent');if(adminState.section==='overview')c.innerHTML=overview(d);else if(adminState.section==='users')c.innerHTML=users(d);else if(adminState.section==='cities')c.innerHTML=cities(d);else if(adminState.section==='activities')c.innerHTML=activities(d);else c.innerHTML=trends(d)}
function overview(d){
  const users=Number(d.summary.users||0), trips=Number(d.summary.trips||0), activities=Number(d.summary.activities||0), publicTrips=Number(d.summary.public_trips||0);
  const latestUsers=d.user_trends?.length?Number(d.user_trends[d.user_trends.length-1].users||0):0;
  const returning=Math.max(0,users-latestUsers);
  const cities=d.popular_cities||[];
  const maxCity=Math.max(1,...cities.slice(0,5).map(x=>Number(x.visits||0)));
  const cityBars=cities.slice(0,5).map((x,i)=>`<div class="city-col"><strong>${Number(x.visits||0)}</strong><i style="height:${Math.max(12,Number(x.visits||0)/maxCity*62)}px"></i><small>${esc(x.city)}</small></div>`).join('');
  const trend=d.user_trends||[];
  const points=trend.slice(-7).map((x,i)=>{const max=Math.max(1,...trend.slice(-7).map(y=>Number(y.users||0)));const xPos=3+(i*94/Math.max(1,trend.slice(-7).length-1));const yPos=72-(Number(x.users||0)/max*55);return `${xPos},${yPos}`}).join(' ');
  const dots=trend.slice(-7).map((x,i)=>{const max=Math.max(1,...trend.slice(-7).map(y=>Number(y.users||0)));const xPos=3+(i*94/Math.max(1,trend.slice(-7).length-1));const yPos=72-(Number(x.users||0)/max*55);return `<circle cx="${xPos}" cy="${yPos}" r="2.2" fill="#2c8fc0"/>`}).join('');
  const labels=trend.slice(-7).map(x=>`<span>${esc(x.month||'')}</span>`).join('');
  return `<div class="dashboard-wrap"><div class="dashboard-main">
    <div class="overview-grid-top">
      <section class="overview-card"><div class="overview-title"><h2>User Overview</h2></div><div class="metric-list">
        <div class="metric-row"><span class="metric-icon">♧</span><div class="metric-copy"><b>${users.toLocaleString('en-IN')} Total Users</b></div><div class="metric-bar"><i style="width:100%"></i></div></div>
        <div class="metric-row"><span class="metric-icon">♙</span><div class="metric-copy"><b>${users.toLocaleString('en-IN')} Active Users</b></div><div class="metric-bar"><i style="width:${users?100:0}%"></i></div></div>
        <div class="metric-row"><span class="metric-icon">♙</span><div class="metric-copy"><b>${latestUsers.toLocaleString('en-IN')} New Users</b></div><div class="metric-bar"><i style="width:${users?Math.max(8,latestUsers/users*100):0}%"></i></div></div>
        <div class="metric-row"><span class="metric-icon">↻</span><div class="metric-copy"><b>${returning.toLocaleString('en-IN')} Returning Users</b></div><div class="metric-bar"><i style="width:${users?Math.max(8,returning/users*100):0}%"></i></div></div>
      </div></section>
      <section class="overview-card"><div class="overview-title"><h2>Trip Distribution</h2></div><div class="donut-panel"><div class="donut"></div><div class="legend"><div class="legend-row"><i class="legend-dot blue"></i>Public Trips — ${trips?Math.round(publicTrips/trips*100):0}%</div><div class="legend-row"><i class="legend-dot teal"></i>Private Trips — ${trips?Math.round((trips-publicTrips)/trips*100):0}%</div></div></div></section>
    </div>
    <section class="overview-card growth-card"><div class="overview-title"><h2>User Growth &amp; Engagement</h2><div class="growth-legend"><span class="growth-key"><i></i>New Users</span><span class="growth-key"><i class="alt"></i>Active Users</span></div></div><div class="growth-chart"><div class="growth-lines"></div><svg viewBox="0 0 100 80" preserveAspectRatio="none"><polyline points="${points||'3,70 20,65 38,67 55,54 72,59 94,35'}" fill="none" stroke="#2c8fc0" stroke-width="1.2" vector-effect="non-scaling-stroke"/>${dots}</svg><div class="growth-labels">${labels||'<span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span>'}</div></div></section>
    <div class="bottom-grid"><section class="overview-card"><div class="overview-title"><h2>Popular Cities</h2></div><div class="city-bars">${cityBars||'<div class="empty">No city data yet.</div>'}</div></section>
      <section class="overview-card"><div class="overview-title"><h2>Platform Activity</h2></div><div class="activity-grid">
        <div class="activity-stat"><i class="activity-icon">⌁</i><div><span>Trips Created</span><strong>${trips.toLocaleString('en-IN')}</strong></div></div>
        <div class="activity-stat"><i class="activity-icon">⌖</i><div><span>Activities Added</span><strong>${activities.toLocaleString('en-IN')}</strong></div></div>
        <div class="activity-stat"><i class="activity-icon">⌖</i><div><span>Cities Explored</span><strong>${cities.length.toLocaleString('en-IN')}</strong></div></div>
        <div class="activity-stat"><i class="activity-icon">♧</i><div><span>Shared Itineraries</span><strong>${publicTrips.toLocaleString('en-IN')}</strong></div></div>
      </div></section></div>
  </div><aside class="dashboard-side"><span class="side-badge">ADMIN</span><h2>Admin Controls</h2><p>High-fidelity modern web application UI mockup for a professional travel SaaS product.</p>
    <div class="control-item"><span class="control-icon">♙</span><div><b>Manage Users</b><small>Manage users and explorations and organizations.</small></div></div>
    <div class="control-item"><span class="control-icon">⌖</span><div><b>Popular Cities</b><small>Popular cities, popularities and activities.</small></div></div>
    <div class="control-item"><span class="control-icon">♧</span><div><b>Popular Activities</b><small>Manage activities, popular activities and updates.</small></div></div>
    <div class="control-item"><span class="control-icon">⌁</span><div><b>User Trends &amp; Analytics</b><small>User trends and user itineraries.</small></div></div>
    <div class="side-stats"><div class="side-stat"><span>Total Users</span><strong>${users.toLocaleString('en-IN')}</strong></div><div class="side-stat"><span>Total Trips</span><strong>${trips.toLocaleString('en-IN')}</strong></div><div class="side-stat"><span>Active Today</span><strong>${users.toLocaleString('en-IN')}</strong></div><div class="side-stat"><span>Public Itineraries</span><strong>${publicTrips.toLocaleString('en-IN')}</strong></div></div>
  </aside></div>`
}
function users(d){let list=[...d.recent_users],q=($('#adminSearch')?.value||'').toLowerCase().trim(),f=$('#adminFilter')?.value||'all',s=$('#adminSort')?.value||'latest';list=list.filter(u=>!q||(u.name+' '+u.username+' '+u.email+' '+u.country+' '+u.style).toLowerCase().includes(q));if(f!=='all')list=list.filter(u=>String(u.country).toLowerCase()===f||String(u.style).toLowerCase()===f);if(s==='name')list.sort((a,b)=>a.name.localeCompare(b.name));else list.sort((a,b)=>Number(b.id)-Number(a.id));return `<section class="admin-card"><div class="card-title"><div><h2>Manage Users</h2><p>${list.length} users shown from the database.</p></div></div><div class="table-wrap"><table><thead><tr><th>User</th><th>Username</th><th>Email</th><th>Country</th><th>Style</th><th>Joined</th></tr></thead><tbody>${list.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.username)}</td><td>${esc(u.email)}</td><td>${esc(u.country)}</td><td><span class="pill">${esc(u.style)}</span></td><td>${esc(u.created_at)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No users match the current filters.</td></tr>'}</tbody></table></div></section>`}
function cities(d){return `<section class="admin-card"><div class="card-title"><div><h2>Popular Cities</h2><p>Most frequently selected destinations from saved trip stops.</p></div></div><div class="rank-list">${d.popular_cities.map((x,i)=>`<div class="rank-row"><span class="rank">${i+1}</span><div class="rank-main"><b>${esc(x.city)}</b><div class="rank-bar"><i style="width:${Math.max(8,Number(x.visits)/Math.max(1,Number(d.popular_cities[0]?.visits))*100)}%"></i></div></div><strong>${x.visits}</strong></div>`).join('')}</div></section><section class="admin-card"><div class="card-title"><h2>City Spend Snapshot</h2></div><div class="table-wrap"><table><thead><tr><th>City</th><th>Trips</th><th>Activity Spend</th></tr></thead><tbody>${d.city_costs.map(x=>`<tr><td>${esc(x.city)}</td><td>${x.trips}</td><td>${money(x.activity_spend)}</td></tr>`).join('')}</tbody></table></div></section>`}
function activities(d){return `<section class="admin-card"><div class="card-title"><div><h2>Popular Activities</h2><p>Activity usage and average stored cost from the database.</p></div></div><div class="rank-list">${d.popular_activities.map((x,i)=>`<div class="rank-row"><span class="rank">${i+1}</span><div class="rank-main"><b>${esc(x.name)}</b><small>${esc(x.type)} · Avg. cost ${money(x.avg_cost)}</small><div class="rank-bar"><i style="width:${Math.max(8,Number(x.uses)/Math.max(1,Number(d.popular_activities[0]?.uses))*100)}%"></i></div></div><strong>${x.uses}</strong></div>`).join('')}</div></section>`}
function trends(d){return `<section class="admin-grid"><div class="admin-card stat"><span>Registered Users</span><strong>${d.summary.users}</strong><small>Current database count</small></div><div class="admin-card stat"><span>Public Trips</span><strong>${d.summary.public_trips}</strong><small>Trips available for sharing</small></div></section><section class="admin-analytics-grid"><div class="admin-card"><div class="card-title"><h2>User Growth</h2></div>${lineLike(d.user_trends,'users')}</div><div class="admin-card"><div class="card-title"><h2>Trip Creation Trend</h2></div>${lineLike(d.trip_trends,'trips')}</div></section>`}
function barList(items,label,value){const max=Math.max(1,...items.map(x=>Number(x[value]||0)));return `<div class="bar-list">${items.slice(0,6).map(x=>`<div class="bar-item"><div><span>${esc(x[label])}</span><b>${x[value]}</b></div><div class="bar-track"><i style="width:${Math.max(5,Number(x[value]||0)/max*100)}%"></i></div></div>`).join('')}</div>`}
function lineLike(items,key){if(!items.length)return '<div class="empty">Not enough trend data yet.</div>';const max=Math.max(1,...items.map(x=>Number(x[key]||0)));return `<div class="mini-chart">${items.slice(-8).map(x=>`<div class="chart-col"><span>${x[key]}</span><i style="height:${Math.max(12,Number(x[key]||0)/max*150)}px"></i><small>${esc(x.month)}</small></div>`).join('')}</div>`}

document.addEventListener('DOMContentLoaded',()=>{if($('#adminLoginForm'))initLogin();if($('#adminContent'))initPanel()});
